version: '3.9'
name: ci

volumes:
  ci_postgres_data: {}
  ci_postgres_data_backups: {}

services:
  django: &django
    image: ci_local_django
    container_name: ci_local_django
    env_file: !reset []
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_ADMIN_URL=admin
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ci
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=12345678
    ports:
      - '8000:8000'

  postgres:
    image: ci_postgres
    container_name: ci_postgres
    env_file: !reset []
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ci
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ci_postgres_data:/var/lib/postgresql/data
      - ci_postgres_data_backups:/backups:z
    ports:
      - '5432:5432'

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: ci_mailhog
    env_file: !reset []
    ports:
      - '8025:8025'

  redis:
    container_name: ci_redis
    env_file: !reset []

  celeryworker:
    image: ci_celeryworker
    container_name: ci_celeryworker
    env_file: !reset []

  celerybeat:
    image: ci_celerybeat
    container_name: ci_celerybeat
    env_file: !reset []

  flower:
    image: ci_flower
    container_name: ci_flower
    env_file: !reset []
    ports:
      - '5555:5555'

  # docs:
  #   image: ci_docs
  #   container_name: ci_docs
  #   env_file: !reset []
  #   ports:
  #     - '9000:9000'
