version: '3.9'

services:
  django: &django
    expose: []
    ports:
      - '${PORT}:8000'
    command: /start
    labels:
      - "traefik.enable=false"
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: ${COMPOSE_PROJECT_NAME}_local_mailhog
    restart: unless-stopped
    expose: []
    ports:
      - '8025:8025'
    labels:
      - "traefik.enable=false"
    networks:
      - backend

  flower:
    <<: *django
    image: ${COMPOSE_PROJECT_NAME}_local_flower
    container_name: ${COMPOSE_PROJECT_NAME}_local_flower
    expose: []
    ports:
      - '5555:5555'
    command: /start-flower
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - backend

  # docs:
  #   image: ${COMPOSE_PROJECT_NAME}_local_docs
  #   container_name: ${COMPOSE_PROJECT_NAME}_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./backend:/app/backend:z
  #   ports:
  #     - '9000:9000'
  #   command: /start-docs

networks:
  dev-proxy:
    name: dev-proxy
  backend:
    name: backend
